name: Example GitHub Action

on:
  push:
    branches:
      - main  # This triggers the action on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the environment the action will run on
    
    steps:
      - name: shailesh.madne@gramener.com  # Step with your email address
        run: echo "Hello, world!"  # The command to execute in this step
