name: Example GitHub Action

on:
  workflow_dispatch:  # Allows you to manually trigger the action
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: shailesh.madne@gramener.com
        run: echo "Hello, world!"
